export interface Product {
  id: string;
  name: string;
  description: string;
  price: number;
  category: string;
  image: string;
  stock: number;
  featured?: boolean;
}

export const CATEGORIES = ["Electronics", "Fashion", "Home & Tech", "Accessories"];

export const MOCK_PRODUCTS: Product[] = [
  {
    id: "1",
    name: "Noise-Cancelling Headphones Pro",
    description: "Experience silence with our industry-leading noise cancellation technology. Premium sound quality and comfortable fit for all-day listening.",
    price: 299000,
    category: "Electronics",
    image: "https://loremflickr.com/800/800/headphones",
    stock: 45,
    featured: true,
  },
  {
    id: "2",
    name: "Minimalist Smartwatch Gen 4",
    description: "Track your fitness, receive notifications, and look stylish with this sleek smart watch. Battery lasts up to 7 days.",
    price: 199500,
    category: "Electronics",
    image: "https://loremflickr.com/800/800/smartwatch",
    stock: 20,
    featured: true,
  },
  {
    id: "3",
    name: "Classic Leather Backpack",
    description: "Durable and stylish. Perfect for daily commutes or weekend getaways. Features a padded laptop sleeve.",
    price: 89000,
    category: "Fashion",
    image: "https://loremflickr.com/800/800/backpack",
    stock: 15,
    featured: true,
  },
  {
    id: "4",
    name: "Mechanical Keyboard X",
    description: "Tactile feedback, RGB backlighting, and a compact design. The ultimate tool for developers and gamers.",
    price: 149000,
    category: "Accessories",
    image: "https://loremflickr.com/800/800/keyboard",
    stock: 5,
    featured: true,
  },
  {
    id: "5",
    name: "Ceramic Coffee Pour-Over",
    description: "Brew the perfect cup of coffee every morning with this elegant ceramic pour-over set.",
    price: 35000,
    category: "Home & Tech",
    image: "https://loremflickr.com/800/800/coffeemaker",
    stock: 100,
  },
  {
    id: "6",
    name: "Wireless Charging Pad",
    description: "Fast-charge your devices without the clutter of cables. Sleek aluminum finish.",
    price: 45000,
    category: "Accessories",
    image: "https://loremflickr.com/800/800/charger",
    stock: 30,
  },
  {
    id: "7",
    name: "HNB-MD14H Laptop",
    description: "High-performance laptop for productivity and gaming. Features a sleek design and extended battery life.",
    price: 350000,
    category: "Electronics",
    image: "https://loremflickr.com/800/800/laptop",
    stock: 25,
  },
  {
    id: "8",
    name: "APD86 Tablet",
    description: "Lightweight and versatile tablet. Perfect for reading, browsing, and media consumption.",
    price: 150000,
    category: "Electronics",
    image: "https://loremflickr.com/800/800/tablet?lock=1",
    stock: 40,
  },
  {
    id: "9",
    name: "GRB10 Rugged Tablet",
    description: "Durable and weather-resistant tablet for outdoor and industrial use.",
    price: 180000,
    category: "Electronics",
    image: "https://loremflickr.com/800/800/tablet?lock=2",
    stock: 12,
  },
  {
    id: "10",
    name: "A85 Smartphone",
    description: "Next-generation smartphone with an advanced camera system and bezel-less display.",
    price: 120000,
    category: "Electronics",
    image: "https://loremflickr.com/800/800/smartphone",
    stock: 80,
  },
  {
    id: "11",
    name: "H1741 4G Feature Phone",
    description: "Reliable 4G feature phone with long battery life and essential apps.",
    price: 25000,
    category: "Electronics",
    image: "https://loremflickr.com/800/800/cellphone",
    stock: 150,
  },
  {
    id: "12",
    name: "Interactive Flat Panel Display",
    description: "Enhance your presentations and collaborative sessions with this responsive interactive display.",
    price: 850000,
    category: "Electronics",
    image: "https://loremflickr.com/800/800/monitor",
    stock: 8,
  },
  {
    id: "13",
    name: "Hera Pro LED Display",
    description: "Crystal clear LED display perfect for digital signage and advertising.",
    price: 450000,
    category: "Electronics",
    image: "https://loremflickr.com/800/800/ledscreen",
    stock: 15,
  },
  {
    id: "14",
    name: "LCD Splicing Display",
    description: "Create massive, seamless video walls with high-definition LCD splicing panels.",
    price: 1200000,
    category: "Electronics",
    image: "https://loremflickr.com/800/800/monitor?lock=1",
    stock: 5,
  },
  {
    id: "15",
    name: "32HS Smart TV",
    description: "Compact 32-inch Smart TV with built-in streaming apps and HD resolution.",
    price: 130000,
    category: "Home & Tech",
    image: "https://loremflickr.com/800/800/television?lock=1",
    stock: 25,
  },
  {
    id: "16",
    name: "55HF Smart TV",
    description: "Immersive 55-inch 4K Smart TV with HDR support and ultra-thin bezels.",
    price: 350000,
    category: "Home & Tech",
    image: "https://loremflickr.com/800/800/television?lock=2",
    stock: 18,
  },
  {
    id: "17",
    name: "FF2-55N Refrigerator",
    description: "Energy-efficient double-door refrigerator with advanced cooling technology.",
    price: 280000,
    category: "Home & Tech",
    image: "https://loremflickr.com/800/800/refrigerator?lock=1",
    stock: 10,
  },
  {
    id: "18",
    name: "DF2-18 Refrigerator",
    description: "Compact single-door refrigerator, perfect for small kitchens or offices.",
    price: 150000,
    category: "Home & Tech",
    image: "https://loremflickr.com/800/800/refrigerator?lock=2",
    stock: 22,
  },
  {
    id: "19",
    name: "DF2-46 Refrigerator",
    description: "Spacious multi-door refrigerator with smart temperature control and frost-free operation.",
    price: 450000,
    category: "Home & Tech",
    image: "https://loremflickr.com/800/800/refrigerator?lock=3",
    stock: 8,
  },
  {
    id: "20",
    name: "XA21 Air Conditioner",
    description: "Quiet and efficient split air conditioner for rapid room cooling.",
    price: 210000,
    category: "Home & Tech",
    image: "https://loremflickr.com/800/800/airconditioner?lock=1",
    stock: 14,
  },
  {
    id: "21",
    name: "XAB1 Air Conditioner",
    description: "Premium inverter air conditioner with smart Wi-Fi controls and air purification.",
    price: 290000,
    category: "Home & Tech",
    image: "https://loremflickr.com/800/800/airconditioner?lock=2",
    stock: 11,
  },
  {
    id: "22",
    name: "BD-155 Chest Freezer",
    description: "High-capacity chest freezer with fast-freeze functionality and lock.",
    price: 240000,
    category: "Home & Tech",
    image: "https://loremflickr.com/800/800/freezer",
    stock: 7,
  },
  {
    id: "23",
    name: "XPB90-962S Washing Machine",
    description: "Fully automatic front-loading washing machine with multiple wash programs.",
    price: 190000,
    category: "Home & Tech",
    image: "https://loremflickr.com/800/800/washingmachine",
    stock: 16,
  },
  {
    id: "24",
    name: "Microwave Oven",
    description: "Compact microwave oven with auto-cook menus and digital display.",
    price: 45000,
    category: "Home & Tech",
    image: "https://loremflickr.com/800/800/microwave",
    stock: 35,
  },
  {
    id: "25",
    name: "Electric Cooker",
    description: "Multi-purpose electric cooker for rice, steaming, and slow cooking.",
    price: 35000,
    category: "Home & Tech",
    image: "https://loremflickr.com/800/800/ricecooker",
    stock: 45,
  },
  {
    id: "26",
    name: "Solar Street Lamp",
    description: "Bright, weather-resistant solar street lamp with motion sensor. Energy efficient.",
    price: 65000,
    category: "Home & Tech",
    image: "https://loremflickr.com/800/800/streetlamp",
    stock: 100,
  }
];
